services:
  postgres_car_marketplace:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata_car_marketplace:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always

  minio_car_marketplace:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_car_marketplace:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    command: server --console-address ":9001" /data

  flyway_car_marketplace:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres_car_marketplace:5432/marketplace_db -user=admin -password=admin migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - postgres_car_marketplace

volumes:
  pgdata_car_marketplace:
  minio_car_marketplace:
